In [1]:
import torch

## Тензоры - набор правил, которые определяют преобразования между тензорами (тензоры - многомерные массивы)

Простой скаляр может быть представлен в виде тензора ранга 0, вектор - ранга 1, матрица n*n - ранга 2

In [2]:
x = torch.tensor([[0, 0, 1], [1, 1, 1],[0, 0, 0]])
x

tensor([[0, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [3]:
x[0][0] = 5

In [4]:
x

tensor([[5, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [5]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [11]:
tensor = torch.ones(1, 2)
tensor2 = torch.ones(1, 2)
print(tensor)
print(tensor2)
tensor + tensor2

tensor([[1., 1.]])
tensor([[1., 1.]])


tensor([[2., 2.]])

In [8]:
torch.ones(1, 2) + torch.ones(1, 2)

tensor([[2., 2.]])

In [9]:
torch.rand(1).item() # тензор ранга 0, извлечение значения с помощью item 

0.1081470251083374

In [12]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [14]:
cpu_tensor = torch.rand(2)
cpu_tensor.device

device(type='cpu')

In [15]:
gpu_tensor = cpu_tensor.to("cuda")
gpu_tensor.device

device(type='cuda', index=0)

## Тензорные операции

In [16]:
torch.rand(2,2).max() # max value

tensor(0.6589)

In [17]:
torch.rand(2,2).max().item() # standart value

0.7789564728736877

In [19]:
# Изменение типа тензора
# шаг 1
long_tensor = torch.tensor([[0,0,1],[1,1,1],[0,0,0]])
long_tensor.type()

'torch.LongTensor'

In [21]:
# шаг 2
float_tensor = torch.tensor([[0,0,1],[1,1,1],[0,0,0]]).to(dtype=torch.float32)
float_tensor.type()

'torch.FloatTensor'

In [22]:
# хранение результата
random_tensor = torch.rand(2,2)
random_tensor.log2()

tensor([[-1.3374, -0.7406],
        [-0.1430, -0.5599]])

In [23]:
random_tensor.log2_()

tensor([[-1.3374, -0.7406],
        [-0.1430, -0.5599]])

In [25]:
# изменение тензора
flat_tensor = torch.rand(784)
viewed_tensor = flat_tensor.view(1,28,28)
viewed_tensor.shape

torch.Size([1, 28, 28])

In [26]:
reshaped_tensor = flat_tensor.reshape(1,28,28)
reshaped_tensor.shape

torch.Size([1, 28, 28])

Разница view() и reshape(): 

    - view() работает как представление исходного тензора, поэтому если базовые данные будут изменены, представление также изменится (и наоборот)
    
    - reshape() делает это незаметно (рекомендуется)

In [28]:
# изменить размеры тензора
hwc_tensor = torch.rand(640,480,3)
chw_tensor = hwc_tensor.permute(2,0,1)
chw_tensor.shape

torch.Size([3, 640, 480])

## Транслирование тензора (выполнить операции между одним тензором и другим, но меньшего размера)

Можно транслировать:

    1) две размерности равны
    2) одна из размерностей является 1